### ISSUE TITLE
Trouble with loginCallback

### ISSUE THREAD

**Issue by jamiewilson** [fongandrew/meteor-login-components#1]
Hey there. thanks for making this!

I'm having some trouble with callback functions. I've added this to my app:

```
LoginComponents = {
  loginCallback: function() {
    console.log('loginCallback worked');
  }
};
```

But can't get it to fire after logging in. I'm not sure where I'm going wrong. Any direction you could give here would be awesome! thank you.

P.S. I might have missed something, but should this line in [signout_button.js](https://github.com/fongandrew/meteor-login-components/blob/master/signout_button.js#L6) reference _signoutCallback_ instead?

`Meteor.logout(LoginComponents.signoutCallback);`

**Comment by fongandrew** [comment]
Huh, the signout vs logout issue is definitely a bug. Bit swamped right now, but will take a look at it this weekend.

Random hunch, but if you do `LoginComponents.loginCallback = function() { ... }` rather than redefining the `LoginComponents` object altogether, does that work?

**Comment by jamiewilson** [comment]
Yup, that worked! thanks for the quick response.

**Comment by fongandrew** [comment]
Fixed signout vs logout issue. `LoginComponents.logout` is used for consistency with `LoginComponents.login`. `LoginComponents.signout` is deprecated but should still work for now.
